version: '3.8'

# Note: Use 'docker compose' instead of 'docker-compose' in newer Docker versions

services:
  excel-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Mount uploads and outputs directories for persistence
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      # Mount history file for persistence
      - ./history.json:/app/history.json
    environment:
      - PYTHONPATH=/app
      - PORT=8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development service (optional)
  excel-processor-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./history.json:/app/history.json
      - ./frontend/src:/app/frontend/src
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app
      - PORT=8000
      - NODE_ENV=development
    profiles:
      - dev
    restart: unless-stopped 