version: '3.8'

# Note: Use 'docker compose' instead of 'docker-compose' in newer Docker versions

services:
  excel-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:49490:8000"  # Bind to all interfaces for Tailscale access
    volumes:
      # Mount uploads and outputs directories for persistence
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      # Mount history file for persistence
      - ./history.json:/app/history.json
    environment:
      - PYTHONPATH=/app
      - PORT=8000
      - HOST=0.0.0.0  # Ensure backend binds to all interfaces
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

  # Development service (optional)
  excel-processor-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "0.0.0.0:49490:8000"  # Bind to all interfaces for Tailscale access
      - "0.0.0.0:3000:3000"  # Bind to all interfaces for Tailscale access
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
      - ./history.json:/app/history.json
      - ./frontend/src:/app/frontend/src
      - ./backend:/app/backend
    environment:
      - PYTHONPATH=/app
      - PORT=8000
      - HOST=0.0.0.0  # Ensure backend binds to all interfaces
      - NODE_ENV=development
    profiles:
      - dev
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 